/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class la_jitco_jana_ParallelRendererJobProcessor */

#ifndef _Included_la_jitco_jana_ParallelRendererJobProcessor
#define _Included_la_jitco_jana_ParallelRendererJobProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     la_jitco_jana_ParallelRendererJobProcessor
 * Method:    computeExternalDependencyOuts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_la_jitco_jana_ParallelRendererJobProcessor_computeExternalDependencyOuts
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
