Job ID: 5
Precision: double
Multiprecision bits: 64
Sample rate: 44100
Length: 10
External ModOut dependencies: 24, 25
External ModIn dependencies: 29, 33
Module:
Module type: FunctionGenerator
Parameters:
baseFrequency: 0.0
function: Sine
initPhase: 0.0
initLevel: 1.0
Dependent ModIns:
frequency: 26; 24
phase: 27; 32
Module:
Module type: FunctionGenerator
Parameters:
baseFrequency: 0.0
function: Sine
initPhase: 0.0
initLevel: 1.0
Dependent ModIns:
frequency: 30; 25
phase: 31; 28
